name: Docker

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
  repository_dispatch:

env:
  IMAGE_NAME: tor-base

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Test image
        run: |
          echo "Testing the image by checking the publicly visible IP. This takes less than two minutes."
          IP=$(curl -s http://checkip.amazonaws.com)
          IP2=$(docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW $IMAGE_NAME wget -q -O - -T 60 http://checkip.amazonaws.com)
          echo "IP of host:      $IP"
          echo "IP of container: $IP2"
          [[ "$IP" != "$IP2" ]] || exit 1

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u seiferma+github --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=quay.io/seiferma/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
